---
downloads: ~/.ansible-downloads/
general:
    local_home: "{{ lookup('env','HOME') }}"
    user_name: "{{ lookup('env', 'USER') }}"

configure_dotfiles: no
configure_sudoers: no
configure_osx: yes

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ag
  - antigen
  - awscli
  - awless
  - candid82/brew/joker
  - carthage
  - cocoapods
  - coreutils
  - emacs-plus
  - fasd
  - git-flow
  - go
  - jq
  - leiningen
  - kops
  - openconnect
  - rabbitmq
  - rbenv
  - sassc
  - shellcheck
  - terraform
  - telnet
  - wget
  - zsh
  - zsh-completions

homebrew_taps:
  - homebrew/core
  # - caskroom/cask
  # - caskroom/versions
  - d12frosted/emacs-plus
  - wallix/awless

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - authy
  - atom
  # - boot
  - discord
  - docker
  - dropbox
  - flux
  - firefox-developer-edition
  - flycut
  - google-chrome
  - insomnia
  - iterm2
  - java8
  - licecap
  - postico
  - sequel-pro
  - skype
  - slack
  - shiftit
  - spotify
  - telegram
  - tunnelblick
  - typora
  #- vagrant
  #- virtualbox
  - whatsapp
  - zoomus

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "sh ~/conf/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
