---
- name: deploy .osx
  become: yes
  become_user: "{{general.user_name}}"
  template:
    src: files/terminal/.osx
    dest: "{{general.local_home}}/conf/.osx"
    force: no
    owner: "{{general.user_name}}"

- name: deploy .gitignore
  become: yes
  become_user: "{{general.user_name}}"
  template:
    src: files/terminal/.gitignore
    dest: "{{general.local_home}}/conf/.gitignore_global"
    force: no
    owner: "{{general.user_name}}"

- name: symlink .gitignore
  file:
    path: "{{general.local_home}}/.gitignore_global"
    src: "{{general.local_home}}/conf/.gitignore_global" 
    state: link
    force: no
    owner: "{{general.user_name}}"

# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Run .osx dotfiles.
  shell: "{{ osx_script }}"
  changed_when: false
