---
- name: Ensure conf directory exists.
  file:
    path: "{{general.local_home}}/conf"
    state: directory
  become: yes
  become_user: "{{general.user_name}}"

- name: remove conf profiles.clj
  file:
    path: "{{general.local_home}}/conf/profiles"
    state: absent

- name: deploy .~/.lein/profiles
  become: yes
  become_user: "{{general.user_name}}"
  template:
    src: files/profiles.in
    dest: "{{general.local_home}}/conf/profiles"
    force: no
    owner: "{{general.user_name}}"

- name: remove standard zshrc
  file:
    path: "{{general.local_home}}/.lein/profiles.clj"
    state: absent

- name: Create conf folder in home directory
  file:
    path: "{{general.local_home}}/conf/"
    state: directory
    owner: "{{general.user_name}}"

- name: symlink zshrc
  file:
    path: "{{general.local_home}}/.lein/profiles.clj"
    src: "{{general.local_home}}/conf/profiles"
    state: link
    force: no
    owner: "{{general.user_name}}"
