---
- name: remove og profiles
  file:
    path: "{{general.local_home}}/.lein/profiles.clj"
    state: absent

- name: symlink profiles
  file:
    path: "{{general.local_home}}/.lein/profiles.clj"
    src: "/keybase/private/kvlt/dotfiles/profiles"
    state: link
    force: no
    owner: "{{general.user_name}}"
