---
- name: Clone spacemacs repo
  git: repo=https://github.com/syl20bnr/spacemacs.git dest="{{general.local_home}}/.emacs.d"

- name: Ensure conf directory exists.
  file:
    path: "{{general.local_home}}/conf"
    state: directory
  become: yes
  become_user: "{{general.user_name}}"

- name: remove conf spacemacs
  file:
    path: "{{general.local_home}}/conf/spacemacs"
    state: absent

- name: deploy .spacemacs
  become: yes
  become_user: "{{general.user_name}}"
  template:
    src: files/spacemacs.in
    dest: "{{general.local_home}}/conf/spacemacs"
    force: no
    owner: "{{general.user_name}}"

- name: remove standard spacemacs
  file:
    path: "{{general.local_home}}/.spacemacs"
    state: absent

- name: symlink spacemacs
  file:
    path: "{{general.local_home}}/.spacemacs"
    src: "{{general.local_home}}/conf/spacemacs"
    state: link
    force: no
    owner: "{{general.user_name}}"
