---
- name: Clone spacemacs repo
  git: repo=https://github.com/syl20bnr/spacemacs.git dest="{{general.local_home}}/.emacs.d"

- name: remove standard spacemacs
  file:
    path: "{{general.local_home}}/.spacemacs"
    state: absent

- name: symlink spacemacs
  file:
    path: "{{general.local_home}}/.spacemacs"
    src: "/keybase/private/kvlt/dotfiles/spacemacs"
    state: link
    force: no
    owner: "{{general.user_name}}"
